"""Local demo server: laptop runs the backend, the tablet connects over the LAN (technical spec §13, DR-07, A-15).

`uv run python -m shiftmate.cli demo [--reset]` prepares the database (Alembic migrations, then seed or full reset so
the seeded day offsets map to today), prints everything the presenter needs (tablet URL, pairing codes, PINs, console
logins, feature status, firewall hint) and runs one uvicorn worker on all interfaces. `doctor` prints the same status
without starting the server.
"""

from __future__ import annotations

import socket
import sys
from pathlib import Path
from typing import Any

from sqlalchemy import func, inspect
from sqlalchemy.orm import Session

from shiftmate.config import settings
from shiftmate.db import SessionLocal, engine
from shiftmate.models import (
    ConsoleUser,
    Device,
    Machine,
    ModelArtifact,
    Operator,
    PairingCode,
    Site,
    TaskAssignment,
)
from shiftmate.seed import reset_demo, seed_database
from shiftmate.time_util import utc_now

SERVER_DIR = Path(__file__).resolve().parents[1]

# Demo accounts (technical spec §13.1). Operator PINs and console passwords are demo-only seed values.
DEMO_OPERATORS = [
    ("Ravi", "OP-0007", "EX-07", "1234"),
    ("Kumar", "OP-0011", "EX-07", "2468"),
    ("Senthil", "OP-0021", "HT-03", "7777"),
]
DEMO_CONSOLE = [
    ("Supervisor", "sup.priya", "Priya-Demo-2026"),
    ("Safety", "saf.meena", "Meena-Demo-2026"),
    ("Trainer", "trn.arjun", "Arjun-Demo-2026"),
    ("Mechanic", "mec.dinesh", "Dinesh-Demo-2026"),
]


def lan_addresses() -> tuple[str | None, list[str]]:
    """(address of the default-route interface, all other IPv4 addresses). No packets are sent."""
    primary = None
    probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        probe.connect(("10.254.254.254", 1))  # UDP connect only selects a route
        primary = probe.getsockname()[0]
    except OSError:
        pass
    finally:
        probe.close()
    others: list[str] = []
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            ip = info[4][0]
            if ip != primary and not ip.startswith("127.") and ip not in others:
                others.append(ip)
    except OSError:
        pass
    if primary is None or primary.startswith("127."):
        primary = others.pop(0) if others else None
    return primary, others


def alembic_config():
    from alembic.config import Config

    cfg = Config(str(SERVER_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(SERVER_DIR / "alembic"))
    return cfg


def migrate() -> str:
    """Brings the schema to head. A database with tables but no recorded revision (made by `seed`, or a half-run
    `alembic upgrade`) is stamped at head only if it already matches the models."""
    from alembic.runtime.migration import MigrationContext
    from alembic.util.exc import AutogenerateDiffsDetected

    from alembic import command

    cfg = alembic_config()
    tables = set(inspect(engine).get_table_names()) - {"alembic_version"}
    with engine.connect() as conn:
        revision = MigrationContext.configure(conn).get_current_revision()
    if tables and revision is None:
        # Tables but no recorded revision: created by `seed`/create_all, or a half-run `alembic upgrade`
        command.stamp(cfg, "head")
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:
            raise SystemExit(
                "The existing database does not match the current schema. Delete it (server/var/shiftmate.db) "
                "and run the demo command again."
            ) from exc
        return "existing database adopted (stamped at head)"
    command.upgrade(cfg, "head")
    return "schema at head"


def status(db: Session) -> dict[str, Any]:
    counts = {
        "sites": db.query(Site).count(),
        "machines": db.query(Machine).count(),
        "operators": db.query(Operator).count(),
        "console_users": db.query(ConsoleUser).count(),
        "tasks": db.query(TaskAssignment).count(),
        "model_artifacts": db.query(ModelArtifact).count(),
        "paired_devices": db.query(Device).filter(Device.revoked_at.is_(None)).count(),
    }
    codes = [
        (p.code, p.machine_id, p.reusable, p.expires_at)
        for p in db.query(PairingCode).order_by(PairingCode.code)
    ]
    first_task = db.query(func.min(TaskAssignment.planned_date)).scalar()
    return {
        "counts": counts,
        "pairing_codes": codes,
        "first_task_date": first_task,
        "artifacts": [a.artifact_id for a in db.query(ModelArtifact).order_by(ModelArtifact.artifact_id)],
    }


def _static_line(label: str, path: str | None, url: str) -> str:
    if path and Path(path).is_dir():
        return f"  {label:<22}{url}"
    return f"  {label:<22}not served (set {'STATIC_OPERATOR_DIR' if 'app' in url else 'STATIC_CONSOLE_DIR'})"


def banner(port: int, info: dict[str, Any]) -> str:
    primary, others = lan_addresses()
    base = f"http://{primary}:{port}" if primary else f"http://<laptop-ip>:{port}"
    now = utc_now()
    ai = (
        ("on (DeepSeek, key set)" if settings.DEEPSEEK_API_KEY else "ON BUT NO KEY - templates only")
        if settings.AI_ENABLED
        else "off (templates)"
    )
    lines = [
        "",
        "=" * 78,
        "  ShiftMate demo server",
        "=" * 78,
        f"  Tablet server URL     {base}        <- enter this in the app (A0 server setup)",
        *[f"  Other addresses       http://{ip}:{port}" for ip in others],
        f"  Health                {base}/api/v1/health",
        f"  API docs              {base}/docs",
        _static_line("Operator web (/app)", settings.STATIC_OPERATOR_DIR, f"{base}/app/"),
        _static_line("Console (/console)", settings.STATIC_CONSOLE_DIR, f"{base}/console/"),
        "",
        "  Pairing codes         "
        + ", ".join(f"{c} {m}" for c, m, reusable, _ in info["pairing_codes"] if reusable),
        "  Operators (PIN)       "
        + ", ".join(f"{n} {oid} on {m} ({pin})" for n, oid, m, pin in DEMO_OPERATORS),
        "  Console logins        " + ", ".join(f"{u} / {p}" for _, u, p in DEMO_CONSOLE),
        "",
        (
            f"  Data                  {info['counts']['machines']} machines, {info['counts']['operators']} "
            f"operators, {info['counts']['tasks']} tasks (from {info['first_task_date']}), "
            f"models: {', '.join(info['artifacts'])}"
        ),
        f"  Paired devices        {info['counts']['paired_devices']}",
        f"  Language AI           {ai}",
        f"  Forecast feed         {'on (Open-Meteo, needs internet)' if settings.FORECAST_ENABLED else 'off (seeded)'}",
        f"  Fleet simulator       {'on' if settings.FLEET_SIM_ENABLED else 'off'}",
        f"  LAN CORS              {'on' if settings.CORS_ALLOW_LAN else 'off'}",
        f"  Server clock (UTC)    {now:%Y-%m-%d %H:%M:%S} - the tablet clock must be within 5 min (signed requests)",
    ]
    if not settings.DEMO_MODE:
        lines.append(
            "  WARNING               DEMO_MODE is false: pairing codes are single-use and reset is refused"
        )
    if sys.platform == "win32":
        lines += [
            "",
            "  If the tablet cannot reach the server, allow the port once (admin PowerShell):",
            (
                f'    netsh advfirewall firewall add rule name="ShiftMate {port}" dir=in action=allow '
                f"protocol=TCP localport={port}"
            ),
        ]
    lines.append("=" * 78)
    return "\n".join(lines)


def run(*, reset: bool, host: str, port: int, serve: bool, fleet: bool | None) -> None:
    print(f"Database: {migrate()}")
    db = SessionLocal()
    try:
        counts = reset_demo(db) if reset else seed_database(db)
        print(("Reset and re-seeded: " if reset else "Seeded (idempotent): ") + str(counts))
        info = status(db)
    finally:
        db.close()

    settings.CORS_ALLOW_LAN = True  # the tablet / LAN browsers call from their own origins
    if fleet is not None:
        settings.FLEET_SIM_ENABLED = fleet
    print(banner(port, info))
    if not serve:
        return

    import uvicorn

    from shiftmate.main import create_app  # built after the settings above are final

    uvicorn.run(create_app(), host=host, port=port, workers=1, log_level=settings.LOG_LEVEL)
