/**
 * Core Domain Entities & Contract Types
 * Storage-neutral, pure TypeScript representations for industrial equipment decision support.
 */

import type {
  AuditRecord,
  DataQualityState,
  EvidenceCitation,
} from '@/core/evidence/types';

export type { DataQualityState } from '@/core/evidence/types';

export type OperatingStatus = 'NOMINAL' | 'WARNING' | 'CRITICAL' | 'OFFLINE';

export type FaultSeverity = 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export type WorkOrderStatus = 'DRAFT' | 'DISPATCHED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';

export type AuditActionType =
  | 'WORK_ORDER_DISPATCHED'
  | 'RECOMMENDATION_DISMISSED'
  | 'FAULT_ACKNOWLEDGED'
  | 'SYSTEM_RESET'
  | 'TELEMETRY_INGESTED';

/**
 * Asset Entity
 * Represents physical heavy equipment. Internal `id` is distinct from external serial.
 */
export interface Asset {
  id: string; // e.g. "ast_336_001"
  serial_number: string; // e.g. "CAT-336-HEX-8821"
  model: string; // e.g. "336 Hydraulic Excavator"
  category: 'EXCAVATOR' | 'ARTICULATED_TRUCK' | 'WHEEL_LOADER' | 'TRACK_LOADER';
  site_id: string; // e.g. "site_north_quarry"
  site_name: string; // e.g. "North Quarry Operations"
  engine_hours: number;
  fuel_level_pct: number;
  status: OperatingStatus;
  last_contact_at: string; // ISO 8601 UTC
  is_synthetic: boolean;
}

/**
 * Telemetry Measurement Point
 * High-frequency or polled sensor reading with dual timestamps and quality state.
 */
export interface TelemetryPoint {
  id: string; // e.g. "tel_092a_01"
  asset_id: string;
  parameter: string; // e.g. "engine_coolant_temp_c", "engine_oil_pressure_kpa", "fuel_rate_lph"
  value: number;
  unit: string; // e.g. "°C", "kPa", "L/h", "rpm"
  observed_at: string; // Sensor timestamp (UTC ISO 8601)
  ingested_at: string; // Receipt timestamp (UTC ISO 8601)
  quality: DataQualityState;
  raw_input?: string; // Optional raw string payload preservation
}

/**
 * Diagnostic Fault Code
 * J1939-style Diagnostic Trouble Code (SPN / FMI).
 */
export interface DiagnosticFault {
  id: string; // e.g. "flt_092a_01"
  asset_id: string;
  spn: number; // Suspect Parameter Number (e.g. 110 = Engine Coolant Temperature)
  fmi: number; // Failure Mode Identifier (e.g. 0 = Data Valid But Above Normal Operational Range - Most Severe)
  standard_description: string;
  source_interpretation: string;
  severity: FaultSeverity;
  is_active: boolean;
  occurred_at: string; // ISO 8601 UTC
  raw_code: string; // e.g. "SPN 110 FMI 0"
}

/**
 * Advisory Recommendation
 * Decision-support insight generated by the deterministic evaluation engine.
 */
export interface Recommendation {
  id: string; // e.g. "rec_336_001"
  asset_id: string;
  fault_id?: string;
  title: string;
  urgency: 'IMMEDIATE' | 'SCHEDULED' | 'OBSERVE';
  confidence_score: number; // 0.0 to 1.0
  evidence_citations: EvidenceCitation[];
  diagnostic_summary: string;
  recommended_action: string;
  suggested_work_order: {
    title: string;
    priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'EMERGENCY';
    estimated_duration_hours: number;
    required_parts: string[];
  };
  created_at: string; // ISO 8601 UTC
}

/**
 * Work Order Entity
 * Actionable operational task created following human supervisor confirmation.
 */
export interface WorkOrder {
  id: string; // e.g. "wo_20260922_001"
  asset_id: string;
  recommendation_id: string;
  title: string;
  description: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'EMERGENCY';
  status: WorkOrderStatus;
  assigned_technician: string;
  approved_by: string; // Human operator persona name
  approved_at: string; // ISO 8601 UTC
  completed_at?: string;
  notes?: string;
}

/**
 * Audit Event Entity
 * Tamper-evident, immutable audit trail for safety & compliance.
 */
export type AuditEvent = AuditRecord<AuditActionType>;
