"""T20 migration test: `upgrade head` on an empty database, then `alembic check` finds no diff against models.py."""

from pathlib import Path

from alembic.config import Config
from sqlalchemy import create_engine, inspect

from alembic import command

SERVER_DIR = Path(__file__).resolve().parents[1]


def _config(db_path: Path) -> Config:
    cfg = Config(str(SERVER_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(SERVER_DIR / "alembic"))
    cfg.set_main_option("sqlalchemy.url", "sqlite:///" + db_path.as_posix())
    return cfg


def test_upgrade_then_check_has_no_diff(tmp_path):
    cfg = _config(tmp_path / "migrate.db")
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected on any difference

    insp = inspect(create_engine("sqlite:///" + (tmp_path / "migrate.db").as_posix()))
    chain = next(i for i in insp.get_indexes("ledger_entries") if i["name"] == "ledger_chain")
    assert chain["unique"] and "chain_seq IS NOT NULL" in str(chain["dialect_options"].get("sqlite_where"))
    checks = {c["name"] for c in insp.get_check_constraints("follow_ups")}
    assert {"ck_follow_ups_category", "ck_follow_ups_priority", "ck_follow_ups_status"} <= checks


def test_downgrade_to_base_drops_everything(tmp_path):
    cfg = _config(tmp_path / "roundtrip.db")
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    tables = set(
        inspect(create_engine("sqlite:///" + (tmp_path / "roundtrip.db").as_posix())).get_table_names()
    )
    assert tables <= {"alembic_version"}
